Index: gdata/inst/unitTests/Makefile
===================================================================
--- gdata/inst/unitTests/Makefile	(revision 981)
+++ gdata/inst/unitTests/Makefile	(working copy)
@@ -1,14 +1,15 @@
 PKG=gdata
 TOP=../..
 SUITE=doRUnit.R
+R=R
 
 all: inst test
 
 inst: # Install package
 	cd ${TOP}/..;\
-	R CMD INSTALL ${PKG}
+	${R} CMD INSTALL ${PKG}
 
 test: # Run unit tests
 	export RCMDCHECK=FALSE;\
 	cd ${TOP}/tests;\
-	R --vanilla --slave < ${SUITE}
+	${R} --vanilla --slave < ${SUITE}
