TARGET=Compress-Raw-Zlib-2.024

default:
	tar xzf ${TARGET}.tar.gz
	build.bat
	make -f Makefile.win clean

clean:
	rm -rf ${TARGET}
	rm -rf ../inst/perl/share

distclean:
	rm -rf ../inst/perl/darwin-2level
	rm -rf ../inst/perl/MSWin32-x86-multi-thread
